/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ckt_testauxiliarytool_contentfill_MemFillTool */

#ifndef _Included_com_ckt_testauxiliarytool_contentfill_MemFillTool
#define _Included_com_ckt_testauxiliarytool_contentfill_MemFillTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ckt_testauxiliarytool_contentfill_MemFillTool
 * Method:    fillMem
 * Signature: (I)I
 */
JNIEXPORT jlong JNICALL Java_com_ckt_testauxiliarytool_contentfill_MemFillTool_fillMem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ckt_testauxiliarytool_contentfill_MemFillTool
 * Method:    freeMem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ckt_testauxiliarytool_contentfill_MemFillTool_freeMem
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
